"""add role to recipe_ingredient

Revision ID: 22f30766ca37
Revises: a5e890dba9d0
Create Date: 2026-08-13 11:44:36.096603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f30766ca37'
down_revision = 'a5e890dba9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliance', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty', native_enum=False),
               existing_nullable=True)

    with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('MAIN', 'ESSENTIAL', 'OPTIONAL', name='ingredient_role', native_enum=False), nullable=True))

    with op.batch_alter_table('utensil', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utensil', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('appliance', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
